import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-listagem',
  templateUrl: './listagem.page.html',
  styleUrls: ['./listagem.page.scss'],
})
export class ListagemPage implements OnInit {

  constructor() { }

  ngOnInit() {
  }

  matrizFormas = [
    ["Cena básica", "basic-scene.html", "basic-scene.png"],
    ["Planos de recorte", "clipping-planes.html", "clipping-planes.png"],
    ["Padrões personalizados", "custom-patterns.html", "custom-patterns.png"],
    ["Globo multi-marcador", "globe-multi-marker.html", "globe-multi-marker.png"],
    ["Globo", "globe.html", "globe.png"],
    ["Cubo", "hello-cube.html", "hello-cube.png"],
    ["Caixa de buraco", "hole-box.html", "hole-box.png"],
    ["Anel de buraco", "hole-ring.html", "hole-ring.png"],
    ["Movimento da câmera do teclado", "keyboard-camera-move.html", "camera-movement.png"],
    ["Movimento de malha do teclado", "keyboard-mesh-move.html", "mesh-movement.png"],
    ["Cubo mágico", "magic-cube.html", "magic-cube.png"],
    ["Modelo", "model.html", "model.png"],
    ["Caminho parabólico", "parabolic-path.html", "parabolic-path.png"],
    ["Teste de meio portal do teclado", "portal-half-keyboard-test.html", "portal-half-keyboard-test.png"],
    ["Visualização do portal AR", "portal-view-AR.html", "portal-view-AR.png"],
    ["Visualização do portal", "portal-view.html", "portal-view.png"],
    ["Refração", "refraction.html", "refraction.png"],
    ["Sombreador", "shader.html", "shader.png"],
    ["Bolas de sombra", "shadow-balls.html", "shadow-balls.png"],
    ["Sombra", "shadow.html", "shadow.png"],
    ["Teste de máscara", "stencil-test.html", "stencil-test.png"],
    ["Textura", "texture.html", "texture.png"],
    ["Vídeo", "video.html", "video.png"],
    ["Efeito de água AR", "water-effect-AR.html", "water-effect-AR.png"],
  ]


  // links = [
  //   "./barcode.html",
  //   "./basic-scene.html",
  //   "./chemistry.html",
  //   "./clipping-planes.html",
  //   "./custom-patterns.html",
  //   "./globe-multi-marker.html",
  //   "./globe.html",
  //   "./hello-cube.html",
  //   "./hole-box.html",
  //   "./hole-plane-2.html",
  //   "./hole-plane.html",
  //   "./hole-ring.html",
  //   "./index.html",
  //   "./keyboard-camera-move.html",
  //   "./keyboard-mesh-move.html",
  //   "./keyboard.html",
  //   "./magic-cube.html",
  //   "./model.html",
  //   "./parabolic-path-2.html",
  //   "./parabolic-path-3.html",
  //   "./parabolic-path.html",
  //   "./portal-half-keyboard-test.html",
  //   "./portal-view-AR.html",
  //   "./portal-view.html",
  //   "./refraction.html",
  //   "./screen-hole.html",
  //   "./shader.html",
  //   "./shadow-balls.html",
  //   "./shadow.html",
  //   "./skybox-test.html",
  //   "./smoothed-controls.html",
  //   "./stencil-test.html",
  //   "./synchronized-relative-movement.html",
  //   "./texture.html",
  //   "./video.html",
  //   "./water-effect-AR.html",
  //   "./water-effect.html"
  // ]

  // imagens = [
  //   "barcode.png",
  //   "basic-scene.png",
  //   "chemistry.png",
  //   "clipping-planes.png",
  //   "custom-patterns.png",
  //   "globe-multi-marker.png",
  //   "globe.png",
  //   "hello-cube.png",
  //   "hole-box.png",
  //   "hole-plane-2.png",
  //   "hole-plane.png",
  //   "hole-ring.png",
  //   "index.png",
  //   "keyboard-camera-move.png",
  //   "keyboard-mesh-move.png",
  //   "keyboard.png",
  //   "magic-cube.png",
  //   "model.png",
  //   "parabolic-path-2.png",
  //   "parabolic-path-3.png",
  //   "parabolic-path.png",
  //   "portal-half-keyboard-test.png",
  //   "portal-view-AR.png",
  //   "portal-view.png",
  //   "refraction.png",
  //   "screen-hole.png",
  //   "shader.png",
  //   "shadow-balls.png",
  //   "shadow.png",
  //   "skybox-test.png",
  //   "smoothed-controls.png",
  //   "stencil-test.png",
  //   "synchronized-relative-movement.png",
  //   "texture.png",
  //   "video.png",
  //   "water-effect-AR.png",
  //   "water-effect.png"
  // ]

  // nomes = [
  //   "código de barras",
  //   "cena básica",
  //   "química",
  //   "planos de recorte",
  //   "padrões personalizados",
  //   "globo multi-marcador",
  //   "globo",
  //   "olá cubo",
  //   "caixa de buraco",
  //   "plano de buraco 2",
  //   "plano de buraco",
  //   "anel de buraco",
  //   "índice",
  //   "movimento da câmera do teclado",
  //   "movimento de malha do teclado",
  //   "teclado",
  //   "cubo mágico",
  //   "modelo",
  //   "caminho parabólico 2",
  //   "caminho parabólico 3",
  //   "caminho parabólico",
  //   "teste de meio portal do teclado",
  //   "visualização do portal AR",
  //   "visualização do portal",
  //   "refração",
  //   "buraco de tela",
  //   "sombreador",
  //   "bolas de sombra",
  //   "sombra",
  //   "teste skybox",
  //   "controles suavizados",
  //   "teste de máscara",
  //   "movimento relativo sincronizado",
  //   "textura",
  //   "vídeo",
  //   "efeito de água AR",
  //   "efeito de água"
  // ]
}
